---
abstract: "Enables CSS Refreshing without\nReloading Whole Page"
author:
  - unknown
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-AutoReloadCSS
no_index:
  directory:
    - inc
provides:
  Plack::Middleware::AutoReloadCSS:
    file: lib/Plack/Middleware/AutoReloadCSS.pm
    version: 0.02
requires:
  Plack: 0
  parent: 0
  perl: 5.014002
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
